config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'home#index', as: :home

  resources :currencies, only: %i(new create update)

  get 'admin', to: 'currencies#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  validates :value, :to, presence: true

  after_commit { CurrencyRelay.perform_later }

  class << self
    def current
      if where('"to" > ?', Time.zone.now).exists?
        last
      else
        new(value: current_currency)
      end
    end

    private

    def current_currency
      Net::HTTP.get(URI('http://cbr.ru'))[%r{</i>(.*)</div}, 1].sub(',', '.')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies/new
  def new
    @currency = Currency.last || Currency.new
  end

  # POST /currencies
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      format.js do
        if @currency.save
          flash.now[:notice] = 'Currency succesfuly saved!'
          render :success
        else
          render :error
        end
      end
    end
  end

  # PATCH/PUT /currencies/1
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.js do
        if @currency.update(currency_params)
          flash.now[:notice] = 'Currency succesfuly saved!'
          render :success
        else
          render :error
        end
      end
    end
  end

  private

  def currency_params
    params.require(:currency).permit(:value, :to)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def marked_li_with_link_to(name, path, options = {})
    li_options = { class: ('active' if current_page?(path)) }.merge(options[:li_options] || {})
    link_options = options[:link_options] || {}

    content_tag(:li, li_options) { link_to(name, path, link_options) }
  end
end

app/views/application/_footer.html.haml
%footer
  %p © 2016 Vladislav Petrov

app/views/application/_header.html.haml
%nav.navbar.navbar-inverse
  .container

    .navbar-header
      = link_to 'FunBoxTestApp', home_path, class: 'navbar-brand'

    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        = marked_li_with_link_to 'Admin', admin_path

app/views/application/_notification.html.haml
- flash.each do |key, value|
  %div{ class: "alert alert-dismissible alert-#{key == 'notice' ? 'success' : 'danger'}" }
    = value
    %button.close{ type: :button, 'data-dismiss': 'alert', 'aria-label': 'Close' }
      %span{ 'aria-hidden': 'true' } &times;

app/views/currencies/_currency.html.haml
#currency
  %span= '%.2f RUB/USD' % currency.value

app/views/currencies/_form.html.haml
= form_for @currency, remote: true do |f|
  - if @currency.errors.any?
    #error_explanation
      %h2= "#{pluralize(@currency.errors.count, 'error')} prohibited this currency from being saved:"
      %ul
        - @currency.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :value
    = f.text_field :value
  .field
    = f.label :to
    = f.datetime_select :to
  .actions
    = f.submit 'Save'

app/views/currencies/error.js.erb
$("form").replaceWith("<%=j render 'form' %>")

app/views/currencies/new.html.haml
%h1 Force currency

= render 'form'

app/views/currencies/success.js.erb
$("div.alert").remove();
$("form").prepend("<%=j render 'notification' %>")

app/views/home/index.html.haml
%h1 Home page

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}
    %title= content_for(:page_title) || 'FunBoxTestApp'
    /= favicon_link_tag
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', 'data-turbolinks-track' => true, media: 'all', async: true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    .container

      = render 'header'

      = render 'notification'

      .container
        .row
          .col-md-9
            = yield
          .col-md-3
            = render Currency.current

      = render 'footer'